import '@/styles/global.scss';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import ScrollToTop from '@/components/ScrollToTop';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	other: {
		'color-scheme': 'light',
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang='pl'>
			<body>
				<Navbar></Navbar>

				{children}

				<Footer />
				<ScrollToTop />
			</body>
		</html>
	);
}
